const authorsMap={
"Pregnancy-related transverse arch deformation: A subject-specific finite element analysis of the contributions of body weight and tissue stiffness":"X. Li; Zhenghui Lu; Y. Fang; G. Fekete; D. Sun; Y. Gu",
"Foot progression angle modulates knee loading during walking in individuals with flexible flatfoot":"L. Shen; Zhenghui Lu; X. Li; Z. Xia; Y. Xu; C. Zhu; Y. Song; X. Cen; D. Sun; G. Fekete; Y. Gu",
"Speed-related increases in plantar tissue stress without affected-side laterality in individuals with unilateral shoulder dislocation":"Zhenghui Lu; L. Xiao; P. Liang; M. Chen; L. Guo; L. Ma; D. Li",
"Region-specific Plantar Fascia Stress Responses to Carbon-fiber Plate Stiffness During Running: A Dynamic Explicit Finite Element Analysis":"Y. Qian; Z. Xia; Y. Song; X. Cen; C. Zhu; Zhenghui Lu; Y. Xu; Z. Zheng; Q. Zeng; D. Sun; J. Sárosi; I. Bíró; Y. Gu",
"Heterogeneous Neuromuscular Control Strategies in the Soccer Instep Kick: A Cross-Sectional Study of Synergy Structure Mapping Across Skill Levels":"D. Wang; D. Sun; F. Li; D. Chen; Z. Zhou; R. Zhao; Zhenghui Lu; Y. Li; Z. Gao; M. Jemni; X. Cen; Y. Song; Y. Gu",
"Foot progression angle modulates three-dimensional lower-limb biomechanics in flexible flatfoot: Kinematic–kinetic patterns and clinical implications":"L. Shen; D. Sun; Y. Fang; Zhenghui Lu; X. Li; Y. Xu; Y. Song; C. Zhu; X. Cen; G. Fekete; M. Jemni",
"Computationally tuned dual-layer lattice pads adapted to gait-induced pressure distribution":"Zhenghui Lu; X. Li; D. Sun; Y. Song; G. Fekete; A. Kovács; Z. Gao; J. Zheng; L. Xiang; Y. Gu",
"The effects of different carbon-fiber plate shapes in shoes on lower limb biomechanics following running-induced fatigue":"Y. Xu; C. Zhu; Y. Fang; Zhenghui Lu; Y. Song; C. Hu; D. Sun; Y. Gu",
"Biomechanical effects of asymmetric backpack shoulder straps on the unilateral flatfoot: A finite element analysis":"C. Hu; X. Cen; D. Sun; Zhenghui Lu; Y. Xu; C. Zhu; Y. Xu; Y. Gu",
"Advances and future directions of foetal finite element modelling in childbirth: From biomechanical interactions to clinical implications":"L. Shen; Zhenghui Lu; X. Li; D. Sun; Y. Song; G. Fekete; A. Kovács; F. Li; X. Cen",
"Will this be the next step? A systematic review of 3D printing in footwear biomechanics":"Zhenghui Lu; X. Li; D. Sun; Y. Song; G. Fekete; A. Kovács; Y. Gu",
"Integrating footwear features into fatigue prediction models for marathon runners: A hybrid CNN-LSTM approach":"C. Zhu; D. Sun; Y. Xu; Zhenghui Lu; C. Hu; X. Cen; Y. Song; Z. Gao; Y. Gu",
"Parametric cushioning lattice insole based on finite element method and machine learning: A preliminary computational analysis":"Zhenghui Lu; X. Li; D. Sun; Y. Song; G. Fekete; A. Kovács; A. Kámán; Y. Gu",
"Sedentary duration and systemic health burden: Nonlinear associations with muscle, fat, and vascular phenotypes in a US population-based study":"C. Hu; Y. Song; D. Sun; Zhenghui Lu; H. Chen; X. Cen; D. Janícijevíc; Z. Radák; Z. Gao; J. S. Baker; Y. Gu",
"Impact of Becker muscular dystrophy on gait patterns: Insights from biomechanical analysis":"S. Gao; Y. Song; D. Sun; X. Cen; M. Wang; Zhenghui Lu; Y. Gu",
"The effect of simulated basketball game load on patellar tendon load during stop-jump movement":"D. Wang; F. Li; J. S. Baker; P. Zhang; Zhenghui Lu; J. Yu; M. Liang",
"Mixed comparison of intervention with eccentric, isometric, and heavy slow resistance for Victorian Institute of Sport Assessment Patella Questionnaire in adults with patellar tendinopathy: A systematic review and network meta-analysis":"Y. Li; D. Sun; Y. Fang; Zhenghui Lu; F. Shi; G. Liu; Y. Gu",
"Pregnancy-induced gait alterations: Meta-regression evidence of spatiotemporal adjustments":"X. Li; Zhenghui Lu; Y. Song; M. Liang; Y. Yuan; G. Fekete; A. Kovács; D. Sun; Y. Gu",
"Effect of pregnancy on female gait characteristics: A pilot study based on portable gait analyzer and induced acceleration analysis":"X. Li; Zhenghui Lu; X. Cen; Y. Zhou; R. Xuan; D. Sun; Y. Gu",
"Case study: The influence of Achilles tendon rupture on knee joint stress during counter-movement jump—Combining musculoskeletal modeling and finite element analysis":"Zhenghui Lu; D. Sun; B. Kovács; Z. Radák; Y. Gu",
"The effects of ankle dorsiflexor fatigue on lower limb biomechanics during badminton forward forehand and backhand lunge":"J. Tong; Zhenghui Lu; X. Cen; C. Chen; U. C. Ugbolue; Y. Gu",
"Comparative efficacy of vibration foam rolling and cold water immersion in amateur basketball players after a simulated load of basketball game":"F. Li; Y. Song; X. Cen; D. Sun; Zhenghui Lu; I. Bíró; Y. Gu",
"The effect of fatigue on lower limb joint stiffness at different walking speeds":"E. Shao; Zhenghui Lu; X. Cen; Z. Zheng; D. Sun; Y. Gu",
"Effect of heel lift insoles on lower extremity muscle activation and joint work during barbell squats":"Zhenghui Lu; X. Li; R. Xuan; Y. Song; I. Bíró; M. Liang; Y. Gu",
"A mixed comparisons of aerobic training with different volumes and intensities of physical exercise in patients with hypertension: A systematic review and network meta-analysis":"Zhenghui Lu; Y. Song; H. Chen; S. Li; E. C. Teo; Y. Gu",
"The influence of a shoe’s heel-toe drop on gait parameters during the third trimester of pregnancy":"X. Li; Zhenghui Lu; D. Sun; R. Xuan; Z. Zheng; Y. Gu",
"The influence of different rope jumping methods on adolescents’ lower limb biomechanics during the ground-contact phase":"Y. Lin; Zhenghui Lu; X. Cen; A. Thirupathi; D. Sun; Y. Gu",
"Influence of different load conditions on lower extremity biomechanics during the lunge squat in novice men":"L. Gao; Zhenghui Lu; M. Liang; J. S. Baker; Y. Gu",
"Effect of rearfoot valgus on biomechanics during barbell squatting: A study based on OpenSim musculoskeletal modeling":"Zhenghui Lu; X. Li; M. Rong; J. S. Baker; Y. Gu",
"A mixed comparisons of different intensities and types of physical exercise in patients with diseases related to oxidative stress: A systematic review and network meta-analysis":"Zhenghui Lu; Y. Xu; Y. Song; I. Bíró; Y. Gu",
"Gait characteristics and fatigue profiles when standing on surfaces with different hardness: Gait analysis and machine learning algorithms":"Zhenghui Lu; D. Sun; D. Xu; X. Li; J. S. Baker; Y. Gu",
"A comparative biomechanical analysis during planned and unplanned gait termination in individuals with different arch stiffnesses":"X. Cen; Zhenghui Lu; J. S. Baker; I. Bíró; Y. Gu",
"The differences in lower extremity joints energy dissipation strategy during landing between athletes with symptomatic patellar tendinopathy and without patellar tendinopathy":"D. Xu; Zhenghui Lu; S. Shen; G. Fekete; U. C. Ugbolue; Y. Gu"
};

const detailMap={
"Pregnancy-related transverse arch deformation: A subject-specific finite element analysis of the contributions of body weight and tissue stiffness":{en:"Pregnancy changes both body mass and the mechanical properties of foot tissues, making it difficult to determine which factors drive transverse-arch deformation. This study used a subject-specific finite element model to separate the effects of increased body weight from tissue softening and to examine their influence on plantar loading. The findings clarify how these two mechanisms jointly contribute to pregnancy-related changes in foot structure and mechanics.",zh:"妊娠过程中体重和足部组织力学性质都会发生变化，因此很难单独判断哪些因素导致足横弓变形。本研究建立个体化有限元模型，将体重增加与组织软化的作用分开分析，并观察它们对足部结构和足底负荷的影响。研究结果有助于解释这两种机制如何共同参与妊娠期足部结构与力学变化。"},
"Foot progression angle modulates knee loading during walking in individuals with flexible flatfoot":{en:"Flexible flatfoot can alter lower-limb alignment and influence how load is transmitted through the knee. Gait data from neutral, toe-in and toe-out conditions were combined with musculoskeletal modeling and a knee finite element model to examine tibiofemoral and meniscal loading. The work shows that changing foot progression angle redistributes internal knee loading and supports individualized gait modification.",zh:"柔性扁平足会改变下肢排列，并影响步行时膝关节内部负荷的传递。本研究比较中性、内八和外八足进展角条件，并结合肌肉骨骼建模与膝关节有限元模型分析胫股关节及半月板负荷。结果显示，足进展角调整会重新分配膝关节内部受力，因此步态干预更适合采用个体化策略。"},
"Speed-related increases in plantar tissue stress without affected-side laterality in individuals with unilateral shoulder dislocation":{en:"Unilateral shoulder injury may change trunk and upper-limb control during gait, but it is unclear whether this creates side-specific foot loading. Participants walked at different speeds while plantar loading was measured and finite element analysis was used to estimate internal tissue stress. Faster walking increased forefoot and plantar-tissue loading, whereas the feet remained broadly symmetric relative to the injured shoulder side.",zh:"单侧肩关节损伤可能改变步行时的躯干和上肢控制，但是否会进一步造成足部左右侧负荷差异并不明确。本研究比较不同步行速度下的足底外部负荷，并利用有限元模型估计足部内部组织应力。结果显示，速度增加会提高前足和足底组织负荷，但相对于肩部患侧并未形成明显的足部侧别差异。"},
"Region-specific Plantar Fascia Stress Responses to Carbon-fiber Plate Stiffness During Running: A Dynamic Explicit Finite Element Analysis":{en:"Carbon-fiber plates alter shoe bending stiffness and can change how load is transferred through the foot during running. This subject-specific study used dynamic explicit finite element modeling to compare plantar-fascia stress across functional regions under different plate stiffness conditions. The results show that plate stiffness changes the regional distribution of plantar-fascia loading rather than affecting the tissue uniformly.",zh:"碳纤维板会改变鞋具弯曲刚度，并影响跑步过程中足部负荷的传递。本研究采用个体化动态显式有限元模型，对不同碳板刚度条件下足底筋膜各功能区域的应力进行比较。结果显示，碳板刚度主要通过改变区域性负荷分布影响足底筋膜，而不是对整个组织产生一致作用。"},
"Heterogeneous Neuromuscular Control Strategies in the Soccer Instep Kick: A Cross-Sectional Study of Synergy Structure Mapping Across Skill Levels":{en:"The soccer instep kick requires coordinated activation of multiple lower-limb muscles, and the organization of this control may vary with skill level. Surface EMG and muscle-synergy analysis were used to map common and skill-specific neuromuscular patterns. The study identified shared basic synergies while showing that more skilled players organized muscle contributions in a more concentrated and differentiated manner.",zh:"足球脚背踢球需要多块下肢肌肉高度协调，而这种神经肌肉控制的组织方式可能随技能水平而变化。本研究结合表面肌电和肌肉协同分析，对共同及技能特异性协同模式进行映射。结果显示，不同水平运动员存在共享的基本协同结构，但高水平运动员的肌肉贡献更加集中和分化。"},
"Foot progression angle modulates three-dimensional lower-limb biomechanics in flexible flatfoot: Kinematic–kinetic patterns and clinical implications":{en:"Foot progression angle is an easily modifiable gait parameter that can influence lower-limb alignment and loading in flexible flatfoot. Participants walked with different progression-angle strategies while three-dimensional kinematics and kinetics were analyzed. Toe-in, neutral and toe-out strategies produced distinct ankle and knee mechanical patterns, highlighting the need for individualized gait modification.",zh:"足进展角是一个容易调整的步态参数，但会影响柔性扁平足人群的下肢排列和负荷。本研究比较不同足进展角条件下的三维运动学与动力学。结果显示，内八、中性和外八步态会形成不同的踝膝力学模式，提示步态调整需要结合个体特征。"},
"Computationally tuned dual-layer lattice pads adapted to gait-induced pressure distribution":{en:"Localized forefoot overload is difficult to manage with conventional uniform-stiffness cushioning because plantar-pressure patterns vary between individuals. This study combined finite element simulation, Gaussian-process surrogate modeling and Bayesian optimization to tune a dual-layer lattice pad to gait-induced pressure distribution. The optimized architecture redistributed plantar load more effectively and demonstrated how personalized pressure data can be translated into a manufacturable lattice design.",zh:"传统均匀刚度缓冲结构难以适应不同个体的局部前足高负荷。本研究结合有限元仿真、高斯过程代理模型和贝叶斯优化，根据步态产生的足底压力分布对双层晶格垫进行优化。优化结构能够更有效地重新分配足底负荷，并展示了如何将个体压力数据转化为可制造的个性化晶格设计。",image:"https://media.springernature.com/lw1200/springer-static/image/art%3A10.1038%2Fs44334-025-00055-8/MediaObjects/44334_2025_55_Fig3_HTML.png"},
"The effects of different carbon-fiber plate shapes in shoes on lower limb biomechanics following running-induced fatigue":{en:"Carbon-fiber plates are increasingly used in running shoes, but plate geometry may interact with fatigue-related changes in running mechanics. Runners were tested before and after a fatigue protocol while wearing shoes with different plate shapes, with lower-limb mechanics and muscle activity analyzed. Curved and flat plates produced different forefoot and proximal-joint responses, showing that plate geometry can modify biomechanics after fatigue.",zh:"碳纤维板已广泛用于跑鞋，但板形可能与疲劳后的跑步力学变化产生相互作用。本研究让跑者在疲劳前后穿着不同碳板形状的鞋，并分析下肢关节力学与肌肉活动。结果显示，弯曲板和平板会形成不同的前足及近端关节响应，说明碳板几何能够影响疲劳后的跑步生物力学。"},
"Biomechanical effects of asymmetric backpack shoulder straps on the unilateral flatfoot: A finite element analysis":{en:"Asymmetric backpack loading may change whole-body posture and alter the mechanical environment of an already asymmetric foot. A finite element model of unilateral flatfoot was used to compare plantar-fascia, Achilles-tendon and arch mechanics under different shoulder-strap configurations. Symmetric straps generally produced a more balanced soft-tissue loading pattern, whereas strap asymmetry shifted arch mechanics and increased local tissue demand.",zh:"不对称背包负荷可能改变整体姿势，并进一步影响本身已存在左右差异的足部力学环境。本研究利用单侧扁平足有限元模型，对不同肩带配置下的足底筋膜、跟腱和足弓力学进行比较。结果显示，对称肩带总体上形成更均衡的软组织负荷，而不对称配置会改变足弓力学并增加局部组织负担。"},
"Will this be the next step? A systematic review of 3D printing in footwear biomechanics":{en:"Additive manufacturing offers new freedom for tailoring footwear geometry and mechanical properties, but the biomechanical evidence remains fragmented. This systematic review synthesizes studies of 3D-printed footwear for injury prevention, comfort and athletic performance and compares their design and evaluation approaches. The literature shows strong potential for personalization while also revealing methodological heterogeneity and a need for stronger validation and user-specific design frameworks.",zh:"增材制造为鞋具几何形态和力学性能的个体化设计提供了更高自由度，但相关生物力学证据仍较分散。本系统综述整合 3D 打印鞋具在损伤预防、舒适性和运动表现方面的研究，并比较不同设计与评价方法。现有证据显示个体化应用具有明显潜力，同时也暴露出方法差异较大、验证不足以及需要建立用户特异性设计框架等问题。",image:"https://www.tandfonline.com/action/showGraphicalAbstractImage?doi=10.1080%2F19424280.2025.2472251&id=tfws_a_2472251_uf0001_c.jpg"},
"Parametric cushioning lattice insole based on finite element method and machine learning: A preliminary computational analysis":{en:"Personalized lattice insoles require a controllable way to connect structural parameters with cushioning performance. This study created a parameterized lattice insole, generated finite element simulations across different structural combinations and trained machine-learning models to rapidly predict mechanical behavior. The workflow identified promising parameter combinations for pressure reduction and demonstrates a route from computational sampling to intelligent footwear optimization.",zh:"个体化晶格鞋垫需要建立一种可控方法，将结构参数与缓冲性能直接联系起来。本研究构建参数化晶格鞋垫，通过有限元生成不同结构组合的力学数据，并训练机器学习模型进行快速性能预测。该流程能够筛选更有利于缓冲和减压的参数组合，展示了从计算仿真到智能鞋具优化的可行路径。"}
};

const extraOutputs=[
{year:"2026",position:"prepend",title:"Knee joint biomechanics during lunges at different tibial angles and external loads: a musculoskeletal analysis with finite element insights",meta:"Computer Methods in Biomechanics and Biomedical Engineering · 2026",authors:"L. Gao; S. Gao; Zhenghui Lu; G. Fekete; Z. Gao",href:"https://doi.org/10.1080/10255842.2026.2737738",en:"Lunge technique and external load can substantially change the mechanical demand placed on the knee, yet their combined effects are not always clear. This study combined musculoskeletal modeling with finite element analysis to compare knee mechanics across different tibial-angle and loading conditions. The results show that both technique and external resistance alter joint moments, stiffness and meniscal loading, providing a biomechanical basis for lunge-based training and rehabilitation.",zh:"弓步动作技术和外部负荷都会改变膝关节的机械需求，但二者的联合影响并不完全清楚。本研究将肌肉骨骼建模与有限元分析结合，比较不同胫骨角度和负荷条件下的膝关节力学。结果显示，动作角度和外部阻力都会改变关节力矩、刚度及半月板负荷，为弓步训练和康复中的动作选择提供了生物力学依据。"},
{year:"2025",title:"Personalised footwear design method based on machine learning and finite element analysis",meta:"Footwear Science · 2025 · Symposium paper · First author",authors:"Zhenghui Lu; X. Li; D. Sun; G. Fekete; A. Kovács; Y. Gu",href:"https://doi.org/10.1080/19424280.2025.2493755",en:"Personalized footwear design requires a rapid way to connect structural parameters with foot–shoe mechanical response. This symposium paper combines lattice-structure finite element simulations, machine-learning prediction and a subject-specific foot–shoe model within an optimization workflow. The approach demonstrates how computational models can be used to search footwear design parameters that reduce plantar loading for an individual user.",zh:"个体化鞋具设计需要快速建立结构参数与足鞋力学响应之间的联系。本会议论文将晶格结构有限元仿真、机器学习预测和个体化足鞋模型整合到优化流程中。该方法展示了如何利用计算模型搜索更适合个体用户、能够降低足底负荷的鞋具设计参数。"},
{year:"2025",title:"Biomechanical impact of weight gain and ligament relaxation on arch deformation during pregnancy: a Finite Element Analysis",meta:"Footwear Science · 2025 · Symposium paper",authors:"X. Li; Zhenghui Lu; A. Kovács; G. Fekete; Y. Gu",href:"https://doi.org/10.1080/19424280.2025.2493747",en:"Pregnancy-related foot deformation develops while body weight increases and passive tissues become more compliant, making their individual roles difficult to separate experimentally. This finite element study modeled these factors independently to examine their effects on arch deformation and plantar loading. The work helps clarify the mechanical pathways through which pregnancy can alter foot structure.",zh:"妊娠期足部变形往往伴随体重增加和被动组织松弛，因此实验中很难区分两类因素各自的作用。本研究利用有限元模型分别模拟这些变化，并分析其对足弓变形和足底负荷的影响。研究有助于解释妊娠过程中足部结构改变背后的力学机制。"},
{year:"2024",title:"Tool wear prediction in milling CFRP with different fiber orientations based on multi-channel 1DCNN-LSTM",meta:"Journal of Intelligent Manufacturing · 2024",authors:"B. Li; Zhenghui Lu; X. Jin; L. Zhao",href:"https://doi.org/10.1007/s10845-023-02164-7",en:"Tool wear during CFRP machining depends strongly on fiber orientation and produces complex, time-varying cutting-force signals. This study developed a multi-channel 1DCNN-LSTM model that learns spatial and temporal features from cutting-force data across different machining conditions. The model provides a data-driven approach for predicting tool wear in anisotropic composite machining and demonstrates the broader use of deep learning for manufacturing-process monitoring.",zh:"CFRP 加工中的刀具磨损受纤维方向影响明显，同时切削力信号具有复杂的时序变化。本研究构建多通道 1DCNN-LSTM 模型，从不同加工条件下的切削力数据中提取空间与时间特征，用于预测刀具磨损。该工作展示了深度学习在各向异性复合材料加工过程监测中的应用价值。"},
{year:"2024",title:"The Impact of Shoe Heel-Toe Drop on Plantar Pressure During the Third Trimester of Pregnancy",meta:"Advances in Transdisciplinary Engineering · 2024 · Conference proceedings",authors:"X. Li; Zhenghui Lu; Z. Gao; S. Shen; Y. He; G. Fekete; A. Kovács; Y. Gu",href:"https://doi.org/10.3233/ATDE240587",en:"Late pregnancy changes body mass distribution, balance and gait, which may increase forefoot discomfort and instability. This study compared plantar-pressure patterns in third-trimester participants walking in flat and negative-heel footwear. Modifying heel-to-toe drop redistributed plantar load, suggesting that footwear geometry can be used to manage pregnancy-related forefoot loading.",zh:"孕晚期体重分布、平衡和步态都会发生变化，可能增加前足不适和步行不稳定。本研究比较孕晚期女性穿着平底鞋和负跟鞋时的足底压力分布。结果显示，调整鞋跟前后落差能够重新分配足底负荷，说明鞋具几何设计可用于管理妊娠相关的前足负荷。"},
{year:"2024",title:"Customized 3D-Printed Insoles for Diabetic Foot Care: Finite Element Analysis and Machine Learning Approach",meta:"Advances in Transdisciplinary Engineering · 2024 · Conference proceedings · First author",authors:"Zhenghui Lu; X. Li; Z. Gao; H. Chen; Q. Zhang; Y. Xu; G. Fekete; Y. Gu",href:"https://doi.org/10.3233/ATDE240588",en:"Diabetic-foot management often requires reducing localized plantar pressure to lower the risk of ulceration. This study used finite element analysis to compare different 3D-printed insole structures and explored machine learning as a way to select suitable offloading designs. The results support a computational workflow for developing patient-specific printed insoles rather than relying on a single generic cushioning structure.",zh:"糖尿病足管理的重要目标之一是降低局部足底高压，以减少溃疡风险。本研究利用有限元比较不同 3D 打印鞋垫结构的减压效果，并探索机器学习用于筛选合适的卸载设计。结果支持采用计算驱动流程开发患者特异性的打印鞋垫，而不是依赖单一通用缓冲结构。"},
{year:"2024",title:"Biomechanical Analysis of Gymnastics Movements Using Wearable Motion Capture Systems and Linear Sensors: A Case Study of the Kipping Bar Muscle-Up",meta:"Advances in Transdisciplinary Engineering · 2024 · Conference proceedings",authors:"W. Liu; Zhenghui Lu; X. Li; Z. Gao; Y. Xu; Q. Mei; G. Fekete; Y. Gu",href:"https://doi.org/10.3233/ATDE240589",en:"Complex gymnastics skills are difficult to quantify with conventional laboratory setups because they involve rapid whole-body motion and large movement ranges. This case study combined wearable IMU motion capture with a linear position/power sensor to analyze the kipping bar muscle-up. The workflow demonstrates how portable sensing can quantify body motion, joint behavior and power-related characteristics in technically complex sport movements.",zh:"复杂体操动作速度快、全身运动范围大，因此传统实验室设备往往难以完整捕捉其力学特征。本病例研究将可穿戴 IMU 动作捕捉与线性位移/功率传感器结合，用于分析 kipping bar muscle-up。该流程展示了便携式传感技术如何量化复杂专项动作中的身体运动、关节行为和功率特征。"}
];

function applyLanguage(lang){const zh=lang==="zh";document.documentElement.lang=zh?"zh-CN":"en";document.body.classList.toggle("lang-zh-mode",zh);document.body.classList.toggle("lang-en-mode",!zh);document.querySelectorAll(".lang-en").forEach(el=>el.hidden=zh);document.querySelectorAll(".lang-zh").forEach(el=>el.hidden=!zh);document.querySelectorAll('[data-lang="en"]').forEach(b=>b.classList.toggle("active",!zh));document.querySelectorAll('[data-lang="zh"]').forEach(b=>b.classList.toggle("active",zh));localStorage.setItem("preferredLanguage",zh?"zh":"en")}
function scholarUrlFor(title,existing){return existing&&existing.includes("scholar.google")?existing:"https://scholar.google.com/scholar?q="+encodeURIComponent(title)}
function boldLu(authors){return(authors||"Zhenghui Lu et al.").replace(/Zhenghui Lu/g,"<strong>Zhenghui Lu</strong>")}
function genericDetail(summary,title){return summary+` This work forms part of my broader research on biomechanics, computational modeling and data-driven analysis, using the specific methods appropriate to ${title.toLowerCase().includes("review")?"evidence synthesis":"the research question"}.`}
function injectStyles(){if(document.getElementById("runtime-site-styles"))return;const s=document.createElement("style");s.id="runtime-site-styles";s.textContent=`.publication-authors{margin-top:7px;font-size:13px;line-height:1.6;color:#4e4b41;max-width:960px}.publication-authors strong{color:#35442f;font-weight:800}.publication-summary{display:none!important}.publication-detail.has-image{grid-template-columns:minmax(190px,260px) 1fr!important;align-items:start}.publication-detail.no-image{grid-template-columns:1fr!important}.publication-figure{background:#fff7e8;border:1px solid #b9a980;padding:7px;min-height:120px;display:flex;align-items:center;justify-content:center}.publication-figure img{display:block;width:100%;max-height:240px;object-fit:contain;background:#fff}.publication-detail .detail-copy p{font-size:14px;line-height:1.82;color:#4e4b41;margin:0 0 10px}.gallery-source-note{font-family:"Arial Narrow",Arial,sans-serif;font-size:10px;letter-spacing:.08em;text-transform:uppercase;color:#8a825f;text-align:center;margin-top:8px}body:not(.home-vintage) .container{width:min(1180px,92%)}body:not(.home-vintage) .navbar{min-height:72px}body:not(.home-vintage) .site-name{font-family:Georgia,"Times New Roman","Songti SC",serif!important;font-size:20px!important;font-weight:800!important;letter-spacing:.06em!important}body:not(.home-vintage) .nav-links a{font-family:"Arial Narrow",Arial,sans-serif!important;text-transform:uppercase;letter-spacing:.08em;font-size:13px!important;font-weight:600}body:not(.home-vintage) .contact-box .chip-link{background:rgba(255,247,232,.35)!important;border:1px solid #7f8854!important;border-radius:0!important;color:#35442f!important;font-family:"Arial Narrow",Arial,sans-serif!important;text-transform:uppercase;letter-spacing:.05em;padding:8px 12px!important;box-shadow:none!important}body:not(.home-vintage) .contact-box .chip-link:hover{background:#35442f!important;color:#fff7e8!important}.home-vintage .v-projects{position:relative;overflow:visible}.home-vintage .v-projects:before,body:not(.home-vintage) .site-footer:before{content:"";position:absolute;left:0;right:0;top:-10px;height:11px;pointer-events:none;background:linear-gradient(135deg,transparent 74%,#282622 75%) 0 0/16px 11px repeat-x,linear-gradient(225deg,transparent 74%,#282622 75%) 8px 0/16px 11px repeat-x}body:not(.home-vintage) .site-footer{position:relative;margin-top:10px}.selected-presentations-section .timeline{grid-template-columns:repeat(3,minmax(0,1fr))}@media(max-width:920px){.selected-presentations-section .timeline{grid-template-columns:1fr 1fr}}@media(max-width:640px){.publication-detail.has-image{grid-template-columns:1fr!important}.selected-presentations-section .timeline{grid-template-columns:1fr}}`;document.head.appendChild(s)}
function injectLatestOutputs(){if(!location.pathname.endsWith("publications.html"))return;extraOutputs.forEach(o=>{if([...document.querySelectorAll(".publication-title")].some(el=>el.textContent.trim().toLowerCase()===o.title.toLowerCase()))return;const year=[...document.querySelectorAll(".publication-year")].find(h=>h.textContent.trim()===o.year);if(!year)return;let list=year.nextElementSibling;if(!list||!list.classList.contains("publication-list"))return;const a=document.createElement("article");a.className="publication-item";a.dataset.extra="1";a.innerHTML=`<div class="publication-title"><a href="${o.href}">${o.title}</a></div><div class="publication-meta">${o.meta}</div><p class="publication-summary lang-en">${o.en}</p><p class="publication-summary lang-zh">${o.zh}</p>`;authorsMap[o.title]=o.authors;detailMap[o.title]={en:o.en,zh:o.zh};if(o.position==="prepend")list.prepend(a);else list.append(a)})}
function enhancePublicationItem(item){if(item.dataset.enhanced)return;const titleWrap=item.querySelector(".publication-title");if(!titleWrap)return;const oldLink=titleWrap.querySelector("a");const title=(oldLink?oldLink.textContent:titleWrap.textContent).trim();const href=oldLink?oldLink.href:"";const data=detailMap[title]||{};const summaryEn=item.querySelector(".publication-summary.lang-en")?.textContent.trim()||"This publication contributes to my broader work in biomechanics and computational modeling.";const summaryZh=item.querySelector(".publication-summary.lang-zh")?.textContent.trim()||"该成果属于我在生物力学与计算建模方向的研究工作。";titleWrap.innerHTML="";const head=document.createElement("div");head.className="publication-head";const btn=document.createElement("button");btn.type="button";btn.className="publication-toggle";btn.textContent=title;btn.setAttribute("aria-expanded","false");const sl=document.createElement("a");sl.className="scholar-link";sl.href=scholarUrlFor(title,href);sl.target="_blank";sl.rel="noopener noreferrer";sl.textContent="Google Scholar";head.append(btn,sl);titleWrap.appendChild(head);const authors=document.createElement("div");authors.className="publication-authors";authors.innerHTML=boldLu(authorsMap[title]);item.querySelector(".publication-meta")?.after(authors);const detail=document.createElement("div");detail.className=`publication-detail ${data.image?"has-image":"no-image"}`;detail.hidden=true;const fig=data.image?`<div class="publication-figure"><img src="${data.image}" alt="Figure from ${title}" loading="lazy"></div>`:"";const pub=href&&!href.includes("scholar.google")?`<p><a href="${href}" target="_blank" rel="noopener noreferrer"><span class="lang-en">Publisher / article page →</span><span class="lang-zh">期刊 / 论文页面 →</span></a></p>`:"";detail.innerHTML=`${fig}<div class="detail-copy"><p class="lang-en">${data.en||genericDetail(summaryEn,title)}</p><p class="lang-zh">${data.zh||summaryZh+" 该研究进一步从相应的实验、计算建模或证据综合角度回答了具体研究问题，并为后续的生物力学分析或应用提供参考。"}</p>${pub}</div>`;item.appendChild(detail);detail.querySelector("img")?.addEventListener("error",e=>{e.target.closest(".publication-figure")?.remove();detail.className="publication-detail no-image"});btn.addEventListener("click",()=>{detail.hidden=!detail.hidden;btn.setAttribute("aria-expanded",String(!detail.hidden));applyLanguage(localStorage.getItem("preferredLanguage")||"en")});item.dataset.enhanced="1"}
function loadInteriorTheme(){const home=document.body.classList.contains("home-vintage")||location.pathname.endsWith("/")||location.pathname.endsWith("index.html");if(home)return;const l=document.createElement("link");l.rel="stylesheet";l.href="interior.css?v=20261003-6";document.head.appendChild(l)}
function normalizeNavigation(){document.querySelectorAll('.nav-links a[href="research.html"]').forEach(a=>a.href="publications.html");document.querySelectorAll('.nav-links a[href="publications.html"]').forEach((a,i,all)=>{if(all.length>1&&i>0)a.remove()});document.querySelectorAll('[data-lang="zh"]').forEach(b=>{if(b.tagName==="BUTTON")b.textContent="中"});document.querySelectorAll('.site-name').forEach(a=>a.textContent="ZHENGHUI LU")}
async function movePresentations(){if(location.pathname.endsWith("projects.html"))document.querySelectorAll(".section-title").forEach(h=>{if(/Selected Presentations|代表性会议报告/.test(h.textContent))h.closest("section")?.remove()});if(!location.pathname.endsWith("publications.html"))return;try{const html=await fetch("projects.html").then(r=>r.text());const doc=new DOMParser().parseFromString(html,"text/html");const h=[...doc.querySelectorAll(".section-title")].find(x=>/Selected Presentations|代表性会议报告/.test(x.textContent));const sec=h?.closest("section");if(sec){sec.classList.add("selected-presentations-section");document.querySelector("main")?.append(sec)}}catch(e){}}
async function decodeB64Image(img,path){try{const txt=(await fetch(path,{cache:"no-store"}).then(r=>r.text())).trim();if(txt)img.src="data:image/jpeg;base64,"+txt}catch(e){}}
async function loadManagedGallery(root){try{const api="https://api.github.com/repos/luzhenghui1111/zhenghuilu.github.io/contents/assets/about-gallery?ref=main";const items=await fetch(api,{headers:{Accept:"application/vnd.github+json"},cache:"no-store"}).then(r=>{if(!r.ok)throw new Error("gallery api");return r.json()});const imgs=items.filter(x=>x.type==="file"&&/\.(jpe?g|png|webp)$/i.test(x.name)).sort((a,b)=>a.name.localeCompare(b.name,undefined,{numeric:true}));if(!imgs.length)return false;const stage=root.querySelector(".about-carousel-stage")||root.querySelector(".about-carousel-frame")||root;root.querySelectorAll(".about-carousel-slide").forEach(x=>x.remove());imgs.forEach((x,i)=>{const s=document.createElement("div");s.className="about-carousel-slide";const im=document.createElement("img");im.src=x.download_url+"?v="+x.sha;im.alt=x.name.replace(/^\d+[._-]*/,"").replace(/[-_]+/g," ").replace(/\.[^.]+$/,"");im.loading=i?"lazy":"eager";s.appendChild(im);stage.appendChild(s)});root.dataset.managedGallery="1";return true}catch(e){return false}}
async function setupAboutCarousel(){const root=document.querySelector("[data-about-carousel]");if(!root)return;const managed=await loadManagedGallery(root);let slides=[...root.querySelectorAll(".about-carousel-slide")];if(!managed){const paths=[null,"assets/about-ubc-reencoded.b64","assets/about-coast-reencoded.b64","assets/about-industry-reencoded.b64","assets/about-fbs-reencoded.b64"];slides.forEach((s,i)=>{const img=s.querySelector("img");if(i&&img&&paths[i])decodeB64Image(img,paths[i])})}const dots=root.querySelector(".about-carousel-dots"),counter=root.querySelector(".about-carousel-counter");if(dots)dots.innerHTML="";let current=0,timer;slides.forEach((_,i)=>{const b=document.createElement("button");b.type="button";b.setAttribute("aria-label",`Show photo ${i+1}`);b.addEventListener("click",()=>show(i,true));dots?.appendChild(b)});function show(i,reset=false){current=(i+slides.length)%slides.length;slides.forEach((s,j)=>s.classList.toggle("is-active",j===current));dots?.querySelectorAll("button").forEach((d,j)=>d.classList.toggle("active",j===current));if(counter)counter.textContent=`${String(current+1).padStart(2,"0")} / ${String(slides.length).padStart(2,"0")}`;if(reset)restart()}function restart(){clearInterval(timer);timer=setInterval(()=>show(current+1),5200)}root.querySelector(".prev")?.addEventListener("click",()=>show(current-1,true));root.querySelector(".next")?.addEventListener("click",()=>show(current+1,true));root.addEventListener("mouseenter",()=>clearInterval(timer));root.addEventListener("mouseleave",restart);root.addEventListener("keydown",e=>{if(e.key==="ArrowLeft")show(current-1,true);if(e.key==="ArrowRight")show(current+1,true)});if(slides.length){show(0);restart()}}
if(/\/research\.html$/.test(location.pathname))location.replace("publications.html");
document.addEventListener("DOMContentLoaded",async()=>{loadInteriorTheme();injectStyles();normalizeNavigation();injectLatestOutputs();await setupAboutCarousel();document.querySelectorAll(".publication-item").forEach(enhancePublicationItem);await movePresentations();const lang=localStorage.getItem("preferredLanguage")||"en";applyLanguage(lang);document.querySelectorAll("[data-lang]").forEach(b=>b.addEventListener("click",()=>applyLanguage(b.getAttribute("data-lang"))))});